### ISSUE TITLE
Add PULL REQUEST Config

### ISSUE THREAD

**Issue by jotolo** [Krakenstain/python-fastAPI-heroku#6]

**Comment by jotolo** [comment]
@yoandysse Could you assign this issue to me? I will upload a PR today

**Comment by jotolo** [comment]
@yoandysse I don't have writing permission on this project. Please, assign and let me know so I can contribute with those 2 issues.

**Comment by yoandysse** [comment]
> @yoandysse I don't have writing permission on this project. Please, assign and let me know so I can contribute with those 2 issues.

fixed, you have admin role now
